import { neon } from "@neondatabase/serverless";
import "dotenv/config";

async function migrate() {
  const sql = neon(process.env.DATABASE_URL!);

  console.log("Running migrations...");

  await sql`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, name TEXT NOT NULL, password_hash TEXT, avatar_url TEXT, bio TEXT, is_voice_actor BOOLEAN DEFAULT FALSE, role TEXT DEFAULT 'user' CHECK(role IN ('user','admin')), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), suspended_at TIMESTAMPTZ)`;
  await sql`CREATE TABLE IF NOT EXISTS accounts (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, provider TEXT NOT NULL, provider_account_id TEXT NOT NULL, access_token TEXT, refresh_token TEXT, expires_at INTEGER, UNIQUE(provider, provider_account_id))`;
  await sql`CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, session_token TEXT UNIQUE NOT NULL, expires_at TIMESTAMPTZ NOT NULL)`;
  await sql`CREATE TABLE IF NOT EXISTS scripts (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, file_name TEXT NOT NULL, file_path TEXT, raw_text TEXT, parsed_data TEXT NOT NULL, genre TEXT, tone TEXT, status TEXT DEFAULT 'active' CHECK(status IN ('active','flagged','removed')), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS script_analysis (id TEXT PRIMARY KEY, script_id TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE, genre TEXT, tone TEXT, character_arcs TEXT, key_beats TEXT, turning_points TEXT, suggested_voices TEXT, memorisation_difficulty TEXT CHECK(memorisation_difficulty IN ('easy','moderate','hard','very-hard')), estimated_sessions INTEGER DEFAULT 5, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(script_id))`;
  await sql`CREATE TABLE IF NOT EXISTS voice_assignments (id TEXT PRIMARY KEY, script_id TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE, character_name TEXT NOT NULL, voice_config TEXT NOT NULL, UNIQUE(script_id, character_name))`;
  await sql`CREATE TABLE IF NOT EXISTS rehearsal_sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, script_id TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE, my_character TEXT NOT NULL, mode TEXT DEFAULT 'standard', started_at TIMESTAMPTZ DEFAULT NOW(), ended_at TIMESTAMPTZ, duration_secs INTEGER DEFAULT 0, lines_total INTEGER DEFAULT 0, lines_completed INTEGER DEFAULT 0, furthest_line INTEGER DEFAULT 0, loop_count INTEGER DEFAULT 0, wildcard_modifier TEXT, subtext_config TEXT, objective_config TEXT, relationship_config TEXT)`;
  await sql`CREATE TABLE IF NOT EXISTS line_metrics (id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES rehearsal_sessions(id) ON DELETE CASCADE, line_id TEXT NOT NULL, line_index INTEGER NOT NULL, character_name TEXT NOT NULL, timing_ms INTEGER, skipped BOOLEAN DEFAULT FALSE, replayed BOOLEAN DEFAULT FALSE, recorded_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS stumble_events (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, script_id TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE, session_id TEXT NOT NULL REFERENCES rehearsal_sessions(id) ON DELETE CASCADE, line_id TEXT NOT NULL, line_index INTEGER NOT NULL, stumble_type TEXT CHECK(stumble_type IN ('hesitation','misread','long-pause')), recorded_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS annotations (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, script_id TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE, line_id TEXT NOT NULL, note_type TEXT CHECK(note_type IN ('personal','blocking','emotion','director','action','exposition','beat','button')), content TEXT NOT NULL, highlight_color TEXT, voice_memo_url TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS bookmarks (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, script_id TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE, label TEXT NOT NULL, start_line_idx INTEGER NOT NULL, end_line_idx INTEGER NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS subscriptions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, plan_id TEXT NOT NULL, status TEXT DEFAULT 'active' CHECK(status IN ('active','cancelled','past_due','expired')), manifest_payment_id TEXT, manifest_sub_id TEXT, amount_cents INTEGER NOT NULL, period TEXT NOT NULL, minutes_included INTEGER NOT NULL, minutes_used INTEGER DEFAULT 0, voices_included INTEGER NOT NULL, current_period_start TIMESTAMPTZ, current_period_end TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS favorites (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, script_id TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE, PRIMARY KEY (user_id, script_id))`;
  await sql`CREATE TABLE IF NOT EXISTS feature_flags (key TEXT PRIMARY KEY, enabled BOOLEAN DEFAULT TRUE, config TEXT, updated_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY, admin_id TEXT NOT NULL, action TEXT NOT NULL, target_type TEXT, target_id TEXT, details TEXT, created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS performance_notes (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, session_id TEXT NOT NULL REFERENCES rehearsal_sessions(id) ON DELETE CASCADE, line_id TEXT NOT NULL, line_index INTEGER NOT NULL, timestamp_ms INTEGER, note TEXT NOT NULL, category TEXT CHECK(category IN ('pacing','energy','timing','pause','delivery')), severity TEXT CHECK(severity IN ('positive','suggestion','critical')), created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS interpretation_configs (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, script_id TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE, name TEXT NOT NULL, objectives_json TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS director_cut_notes (id TEXT PRIMARY KEY, script_id TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE, line_id TEXT NOT NULL, line_index INTEGER NOT NULL, audio_url TEXT NOT NULL, director_name TEXT NOT NULL, director_id TEXT NOT NULL, note_set_name TEXT DEFAULT 'default', created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS ritual_presets (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, breath_inhale DOUBLE PRECISION DEFAULT 4.0, breath_hold DOUBLE PRECISION DEFAULT 4.0, breath_exhale DOUBLE PRECISION DEFAULT 6.0, breath_cycles INTEGER DEFAULT 3, motivational_audio_url TEXT, countdown_secs INTEGER DEFAULT 5, created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS self_tape_takes (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, script_id TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE, character_name TEXT NOT NULL, take_number INTEGER DEFAULT 1, video_url TEXT, audio_url TEXT, duration_secs INTEGER, is_keeper BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS vault_entries (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, script_id TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE, character_name TEXT NOT NULL, genre TEXT, voice_config TEXT, tags TEXT, last_accessed TIMESTAMPTZ DEFAULT NOW(), created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS voice_print_sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, status TEXT DEFAULT 'in-progress' CHECK(status IN ('in-progress','completed','submitted')), segments_json TEXT NOT NULL DEFAULT '[]', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS scene_exchange_sessions (id TEXT PRIMARY KEY, script_id TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE, host_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, guest_user_id TEXT REFERENCES users(id) ON DELETE SET NULL, status TEXT DEFAULT 'waiting' CHECK(status IN ('waiting','active','completed')), host_character TEXT NOT NULL, guest_character TEXT, created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS masterclass_listings (id TEXT PRIMARY KEY, seller_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, script_title TEXT NOT NULL, take_id TEXT, price_cents INTEGER NOT NULL, description TEXT NOT NULL, audio_commentary_url TEXT, annotation_notes TEXT, rating DOUBLE PRECISION DEFAULT 0, review_count INTEGER DEFAULT 0, purchase_count INTEGER DEFAULT 0, status TEXT DEFAULT 'active' CHECK(status IN ('active','draft','removed')), created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS masterclass_purchases (id TEXT PRIMARY KEY, listing_id TEXT NOT NULL REFERENCES masterclass_listings(id) ON DELETE CASCADE, buyer_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, amount_cents INTEGER NOT NULL, purchased_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS actor_profiles (id TEXT PRIMARY KEY, user_id TEXT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE, display_name TEXT NOT NULL, bio TEXT, voice_samples TEXT DEFAULT '[]', tier1_price INTEGER DEFAULT 300, tier2_price INTEGER DEFAULT 900, tier3_price INTEGER DEFAULT 1900, subscriber_count INTEGER DEFAULT 0, total_earnings INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS pass_subscriptions (id TEXT PRIMARY KEY, fan_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, actor_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, tier INTEGER DEFAULT 1 CHECK(tier IN (1, 2, 3)), monthly_price INTEGER NOT NULL, status TEXT DEFAULT 'active' CHECK(status IN ('active','cancelled','expired')), started_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS pronunciation_dictionary (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, word TEXT NOT NULL, ipa TEXT NOT NULL, reference_audio_url TEXT, client_or_industry TEXT, created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS demo_reel_projects (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, status TEXT DEFAULT 'in-progress' CHECK(status IN ('in-progress','assembled','published')), segments_json TEXT NOT NULL DEFAULT '[]', final_audio_url TEXT, profile_url TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS client_deliveries (id TEXT PRIMARY KEY, voice_actor_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, client_email TEXT NOT NULL, client_name TEXT NOT NULL, project_title TEXT NOT NULL, audio_url TEXT, invoice_cents INTEGER NOT NULL, hours_worked DOUBLE PRECISION NOT NULL, hourly_rate DOUBLE PRECISION NOT NULL, usage_rights TEXT NOT NULL, usage_duration TEXT, status TEXT DEFAULT 'pending' CHECK(status IN ('pending','approved','paid','disputed')), delivery_link TEXT UNIQUE, created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS rate_history (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, job_type TEXT NOT NULL, usage_scope TEXT NOT NULL, quoted_amount INTEGER NOT NULL, outcome TEXT CHECK(outcome IN ('accepted','rejected','negotiated','pending')), client_name TEXT, notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS curriculum_progress (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, genre TEXT NOT NULL, current_level INTEGER DEFAULT 1, completed_scripts TEXT DEFAULT '[]', certification_badge TEXT, updated_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(user_id, genre))`;
  await sql`CREATE TABLE IF NOT EXISTS adr_sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, script_id TEXT REFERENCES scripts(id) ON DELETE SET NULL, reference_audio_url TEXT, reference_video_url TEXT, takes_json TEXT DEFAULT '[]', best_sync_score DOUBLE PRECISION DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS voice_profiles (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, project_name TEXT NOT NULL, character_name TEXT NOT NULL, pitch_center DOUBLE PRECISION, tempo_syllables DOUBLE PRECISION, dominant_resonance DOUBLE PRECISION, emotional_register TEXT, reference_audio TEXT DEFAULT '[]', created_at TIMESTAMPTZ DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS earnings_ledger (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, source TEXT NOT NULL CHECK(source IN ('masterclass','pass','delivery','voice_licensing','coaching')), amount_cents INTEGER NOT NULL, description TEXT, reference_id TEXT, created_at TIMESTAMPTZ DEFAULT NOW())`;

  // Seed feature flags
  const flags = [
    'emotion_detection', 'director_notes', 'sound_effects', 'teleprompter', 'export_audio',
    'multi_character', 'annotations', 'bookmarks', 'performance_analytics', 'ai_coach',
    'subtext_mode', 'emotional_arc', 'script_analysis', 'line_memory', 'objective_obstacle',
    'relationship_dynamics', 'wildcard_mode', 'directors_cut', 'cold_read', 'self_tape',
    'vault', 'ritual_mode', 'sleep_learning', 'voice_print', 'scene_exchange',
    'masterclass', 'pass_memberships', 'studio_dashboard', 'audio_quality', 'pronunciation',
    'breath_detector', 'adr_mode', 'copy_timing', 'voice_consistency', 'demo_reel',
    'client_delivery', 'rate_calculator', 'vo_curriculum',
    'waveform_editor', 'audition_tracker', 'referral_system', 'credit_blocks',
    'voice_chat', 'cloud_storage', 'i18n', 'mobile_app', 'error_tracking', 'invoice_pdf',
  ];
  for (const key of flags) {
    await sql`INSERT INTO feature_flags (key, enabled) VALUES (${key}, true) ON CONFLICT (key) DO NOTHING`;
  }

  console.log("Migration complete!");
}

migrate().catch(console.error);
