import type { VOGenre, CurriculumLevel, CurriculumModule } from "@/types";

export const GENRE_LABELS: Record<VOGenre, string> = {
  commercial: "Commercial",
  audiobook: "Audiobook Narration",
  "e-learning": "E-Learning & Corporate",
  character: "Character & Animation",
  medical: "Medical & Technical",
  promo: "Promo & Imaging",
  podcast: "Podcast & Documentary",
};

export const GENRE_DESCRIPTIONS: Record<VOGenre, string> = {
  commercial: "The bread and butter of voice acting. Learn to sell products and services with warmth, energy, and authenticity across TV, radio, and digital formats.",
  audiobook: "Long-form narrative requires stamina, character differentiation, and the ability to maintain a listener's attention for hours. The fastest-growing VO segment.",
  "e-learning": "Corporate training, educational content, and instructional material. Clear, authoritative, and engaging delivery that makes complex information accessible.",
  character: "Animation, video games, and character work. Transform your voice into distinct personalities with unique vocal signatures, accents, and emotional ranges.",
  medical: "Pharmaceutical advertising, medical training, and health content. Precise pronunciation and authoritative delivery in the highest-paying VO category.",
  promo: "TV and radio promos, station imaging, and trailer narration. High-energy, dramatic delivery that captures attention in seconds.",
  podcast: "Documentary narration, podcast hosting, and audio journalism. Conversational authority that keeps listeners engaged through story and information.",
};

export const LEVEL_LABELS: Record<CurriculumLevel, string> = {
  1: "Foundational",
  2: "Developing",
  3: "Intermediate",
  4: "Advanced",
  5: "Professional",
};

export function getCurriculumModule(genre: VOGenre, level: CurriculumLevel): CurriculumModule {
  const scripts = CURRICULUM_SCRIPTS[genre]?.[level] || [];
  return { genre, level, scripts };
}

const CURRICULUM_SCRIPTS: Record<VOGenre, Record<CurriculumLevel, CurriculumModule["scripts"]>> = {
  commercial: {
    1: [
      { id: "com-1-1", title: "Friendly Coffee Brand", text: "Start your morning the way it was meant to be. Rich, smooth, and perfectly roasted — every cup of Sunrise Blend is crafted from hand-selected beans grown in the highlands of Colombia. Because you deserve a moment that's just for you.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } },
      { id: "com-1-2", title: "Local Car Dealership", text: "This weekend only at Riverside Motors — every vehicle in our lot is priced to move. Zero down, zero interest for 60 months on select models. Trucks, SUVs, sedans — if it has four wheels, we've got a deal for you. Riverside Motors, where the road meets the river.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } },
      { id: "com-1-3", title: "Gentle Skincare", text: "Your skin tells a story. Let it be a beautiful one. Petal & Stone — dermatologist-developed skincare that works with your skin's natural balance. No harsh chemicals. No complicated routines. Just you, naturally radiant.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } },
    ],
    2: [
      { id: "com-2-1", title: "Tech Product Launch", text: "Introducing the all-new Nexus Pro. Thinner. Faster. Smarter. With an AI-powered processor that learns how you work and adapts in real time. Battery life that lasts from sunrise to well past sunset. This isn't just the next generation — it's the next era.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } },
      { id: "com-2-2", title: "Insurance (Warm Authority)", text: "Life changes fast. A new home. A growing family. A business that's finally taking off. At Lighthouse Insurance, we don't just cover what you have — we protect what matters most. Call us. Let's build a plan that grows with you.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } },
      { id: "com-2-3", title: "Fast Food (High Energy)", text: "Hungry? We thought so. The Triple Stack is BACK — three patties, three cheeses, and our secret smoky sauce that keeps you coming back. For a limited time, grab one for just five ninety-nine. The Triple Stack. Only at Burger Republic.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } },
    ],
    3: [
      { id: "com-3-1", title: "Luxury Automotive", text: "There's a road that only exists when you're behind this wheel. Where the engine whispers instead of roars. Where every curve feels like it was carved just for you. The all-new Meridian GTS. Engineered for those who drive, not just arrive.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } },
      { id: "com-3-2", title: "Pharmaceutical (DTC)", text: "Living with moderate to severe plaque psoriasis means living with more than just symptoms. It means missed moments. Cancelled plans. ClearPath may help. In clinical trials, 8 out of 10 patients saw clearer skin in just 12 weeks. Ask your doctor if ClearPath is right for you.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } },
      { id: "com-3-3", title: "Non-Profit (Emotional)", text: "Every night, 1.5 million children in this country go to bed hungry. Not in some distant country. Here. In our cities, our neighbourhoods, our schools. One meal can change a child's entire day. Will you be the one who provides it?", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } },
    ],
    4: [
      { id: "com-4-1", title: "30-Second Hard Sell", text: "Saturday! Saturday! SATURDAY! Monster Truck Madness returns to the Coliseum! Watch ten-ton machines CRUSH, SMASH, and FLY through the air! Tickets start at just fifteen dollars! Kids under five are FREE! This Saturday at seven PM — BE THERE!", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } },
      { id: "com-4-2", title: "Cinematic Trailer", text: "In a world where silence is survival... one voice will shatter everything. This summer, Academy Award winner James Chen stars in... The Last Frequency. In theatres and IMAX, July 18th.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } },
      { id: "com-4-3", title: "Subtle Brand Manifesto", text: "We didn't set out to change the world. We just wanted to make a better cup of coffee. Twenty years later, every bag we roast still starts with a handshake and a promise — from the farmer who grew it, to the hands that will brew it. Some things shouldn't be automated.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } },
    ],
    5: [
      { id: "com-5-1", title: "Live Session Simulation", text: "Okay, let's try this with a bit more warmth on 'family' and can you pick up the pace in the middle section? Also the client wants to hear an alt take that's more conversational, less announcer. Ready? And... Crest isn't just toothpaste. It's your family's first smile of the day. And the last one before bed. For over sixty years, that's been enough for us.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } },
      { id: "com-5-2", title: "Multi-Spot Campaign", text: "Spot A (15 sec): When the sun comes up, so does your energy. Zest Morning Blend — wake up to what's possible. Spot B (30 sec): Some mornings, you need more than coffee. You need a reason to move. Zest Morning Blend is triple-roasted for maximum flavour and minimum bitterness. Available wherever great coffee is sold. Spot C (10 sec): Zest. Wake up to what's possible.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } },
      { id: "com-5-3", title: "Award-Show Promo", text: "They came. They created. They changed the game. Now, the industry gathers to celebrate the voices, the visionaries, and the stories that defined the year. The 47th Annual Golden Voice Awards — live, this Sunday at 8, only on Network One.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } },
    ],
  },
  audiobook: {
    1: [
      { id: "ab-1-1", title: "Simple Narrative", text: "The old house stood at the end of Maple Street, half-hidden behind a wall of overgrown ivy. No one had lived there for years, though the lights sometimes flickered on Thursday evenings. Sarah noticed this the first week she moved to the neighbourhood.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } },
      { id: "ab-1-2", title: "Character Introduction", text: "Detective Maria Santos had a rule: never drink coffee after three in the afternoon. She broke this rule on October 14th, which is why she was still wide awake at midnight when the phone rang. 'Santos,' she answered, already reaching for her coat.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } },
      { id: "ab-1-3", title: "Descriptive Passage", text: "The garden was a riot of colour in late June. Roses climbed the southern wall in shades of crimson and peach. Lavender lined the gravel paths, releasing its scent with every footstep. It was the kind of place that made you forget about time entirely.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } },
    ],
    2: [
      { id: "ab-2-1", title: "Dialogue Scene", text: "'You can't be serious,' Eleanor said, setting down her teacup with more force than she intended. The china rattled against the saucer. Across the table, her brother smiled — that infuriating smile she'd known since childhood. 'Dead serious,' he replied. 'I'm selling the house.'", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } },
      { id: "ab-2-2", title: "Action Sequence", text: "He ran. Through the market stalls, scattering oranges and sending a rack of scarves to the ground. Behind him, footsteps — heavy, determined, closing the gap. A left turn. An alley. A dead end. He spun around, breathing hard, hands raised.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } },
      { id: "ab-2-3", title: "Internal Monologue", text: "She should have said something. That was the thought that followed her home, sat beside her on the bus, and waited at her front door. Three words. That's all it would have taken. But she'd swallowed them, the way she always did, and now they sat like stones in her chest.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } },
    ],
    3: [
      { id: "ab-3-1", title: "Multi-Character Scene", text: "'Order!' Judge Whitfield struck the gavel twice. The courtroom settled into uneasy silence. 'Counsel for the defence?' A young woman rose from her chair. 'Your Honour, my client—' 'Your client,' the judge interrupted, removing her glasses, 'has had quite enough of my patience for one morning.'", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } },
      { id: "ab-3-2", title: "Atmospheric Horror", text: "The temperature dropped first. Not slowly, the way evening cools a room, but all at once — like opening a freezer door. Then the smell: damp earth and something older, something that had no business being inside a building. The lights didn't flicker. They simply... dimmed.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } },
      { id: "ab-3-3", title: "Historical Fiction", text: "London, 1888. The fog that particular evening was of the yellow, choking variety — the kind that tasted of coal and left a film on your teeth. Inspector Graves pulled his collar higher and stepped from the hansom cab into a street that seemed to swallow all light.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } },
    ],
    4: [
      { id: "ab-4-1", title: "Emotional Climax", text: "She found the letter in his coat pocket three days after the funeral. His handwriting — that precise, architectural script she'd teased him about for forty years — covered both sides of a single page. 'My darling,' it began, and she had to sit down, because her legs simply refused to hold her any longer.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } },
      { id: "ab-4-2", title: "Complex Narrator Voice", text: "Now, I should tell you — and I realise I'm interrupting myself here, which is a habit I've been meaning to break for approximately thirty-seven years — that what happened next was entirely my fault. Not in the grand, theatrical sense. In the quiet, stupid, irreversible sense. The kind of fault that looks like nothing at first and costs you everything by morning.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } },
      { id: "ab-4-3", title: "Dialect & Accent Work", text: "'Now see here, lad,' the old fisherman said, pointing a sun-darkened finger toward the horizon. 'When the gulls fly inland, that's the sea telling you something. My da knew it, and his da before him. You don't argue with the sea. You just listen.'", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } },
    ],
    5: [
      { id: "ab-5-1", title: "Chapter Opening Marathon", text: "Chapter One: The man who would change everything arrived on a Tuesday. Chapter Two: She had been waiting for someone like him, though she would never admit it. Chapter Three: The house on Belmoral Drive had its own ideas about who should live there. — Maintain distinct energy and tone for each chapter opening while keeping narrative cohesion.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } },
      { id: "ab-5-2", title: "Full Scene Performance", text: "The restaurant was nearly empty. 'I'm leaving,' Ana said. No preamble. No softening. Just the words, dropped like ice into still water. Marco set down his fork. 'When?' Not where. Not why. When. That single word told her everything about how long he'd known. 'Tomorrow,' she said. 'I have a ticket.' He nodded slowly. 'Then I suppose this is dinner.'", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } },
      { id: "ab-5-3", title: "Non-Fiction Authority", text: "The human brain processes approximately 70,000 thoughts per day. Of those, neuroscientists estimate that roughly 80 percent are negative and 95 percent are repetitive. This means that the vast majority of your mental activity is not only unhelpful — it is literally yesterday's unhelpful thinking, running on an endless loop.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } },
    ],
  },
  "e-learning": {
    1: [{ id: "el-1-1", title: "Safety Training Intro", text: "Welcome to your annual workplace safety refresher. In this module, we'll cover fire evacuation procedures, proper lifting technique, and how to report a hazard. This training takes approximately 15 minutes to complete.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }, { id: "el-1-2", title: "Software Tutorial", text: "To create a new project, click the plus icon in the top left corner of your dashboard. You'll see three template options: blank, standard, and advanced. For most users, we recommend starting with the standard template.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }, { id: "el-1-3", title: "Onboarding Welcome", text: "Welcome to the team. Over the next five days, you'll complete a series of modules designed to help you hit the ground running. Each module takes about ten minutes. Let's start with an overview of our company values.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }],
    2: [{ id: "el-2-1", title: "Compliance Module", text: "Under Section 7 of the Data Protection Act, all employees who handle personally identifiable information must complete this certification annually. Failure to comply may result in disciplinary action. Let's begin with a scenario.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }, { id: "el-2-2", title: "Medical Device Training", text: "Before operating the CardioSync 3000, ensure the device has been calibrated within the last 24 hours. Check the indicator light on the rear panel — green means calibrated, amber means recalibration is recommended.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }, { id: "el-2-3", title: "Leadership Course", text: "Effective feedback has three components: observation, impact, and invitation. First, describe what you observed — specific behaviour, not interpretation. Then, explain the impact it had. Finally, invite the other person into the conversation.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }],
    3: [{ id: "el-3-1", title: "Technical Deep Dive", text: "The API authenticates using OAuth 2.0 with bearer tokens. Each request must include an Authorization header in the format: Bearer followed by your access token. Tokens expire after 3600 seconds and must be refreshed using your refresh token.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }, { id: "el-3-2", title: "Scenario-Based", text: "Imagine this: a customer calls and says their order arrived damaged. They're upset. They want a refund AND a replacement. Company policy allows one or the other. What do you do? Pause the video now and consider your approach before we continue.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }, { id: "el-3-3", title: "Assessment Prompt", text: "Question 4 of 10. A colleague shares confidential client information in a team Slack channel. The information is not sensitive in nature, but the channel includes external contractors. According to our data handling policy, which of the following is the correct next step?", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }],
    4: [{ id: "el-4-1", title: "Executive Briefing", text: "Q3 results reflect a 12% increase in customer acquisition cost, offset by a 23% improvement in lifetime value. The net effect is positive, but the CAC trend requires attention. Let's examine the three primary drivers.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }, { id: "el-4-2", title: "Crisis Simulation", text: "ALERT: A critical system failure has been detected in the production environment. All hands on deck. In this simulation, you'll assume the role of incident commander. Your first task: assess scope, assign roles, and establish communication channels within 90 seconds.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }, { id: "el-4-3", title: "Multi-Language Support", text: "This module is available in English, Spanish, Mandarin, and French. To change the language, select the globe icon in the upper right corner. All assessment questions will appear in your selected language. Subtitles are available for all video content.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }],
    5: [{ id: "el-5-1", title: "Full Course Intro", text: "Welcome to Mastering Project Management — a twelve-part series designed for mid-level managers transitioning into programme leadership. Over the coming weeks, we'll cover scope definition, stakeholder mapping, risk frameworks, and the art of saying 'no' diplomatically. I'm your instructor, and I've managed projects that went brilliantly — and a few that taught me everything I know.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }, { id: "el-5-2", title: "Interactive Branching", text: "You chose Option B: Escalate to your manager. Here's what happens. Your manager schedules a meeting with the client for Friday. However, by Wednesday, the client has already posted a negative review online. Was escalation the right call? Let's rewind and explore what might have happened with a different approach.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }, { id: "el-5-3", title: "Certification Exam Intro", text: "You are about to begin the final certification exam. You have 60 minutes to complete 40 questions. A passing score is 80% or higher. You may not return to previous questions once submitted. Your screen will display a timer in the upper right corner. Take a deep breath. You've prepared for this. Good luck.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }],
  },
  character: {
    1: [{ id: "ch-1-1", title: "Friendly Cartoon Sidekick", text: "Hey! Hey! Over here! Did you see that? A butterfly! No wait — TWO butterflies! This is the best day EVER! Come on, let's follow them! They're going toward the waterfall! ADVENTURE TIME!", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }, { id: "ch-1-2", title: "Wise Elder", text: "Listen carefully, young one. The path ahead is not the one you see with your eyes. It is the one you feel with your heart. Many have walked this forest before you. Not all of them walked out.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }, { id: "ch-1-3", title: "Robot Assistant", text: "Good morning. I have completed my analysis of the data. There are three anomalies that require your attention. Shall I display them on the main screen? Also, your coffee is ready. I took the liberty of adjusting the temperature to your preferred 63 degrees.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }],
    2: [{ id: "ch-2-1", title: "Villain Monologue", text: "You think you've won? How delightfully naive. Everything — every battle, every sacrifice, every precious little victory — has been exactly what I planned. You've been dancing to my music this entire time. And now... the finale.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }, { id: "ch-2-2", title: "Scared Child", text: "I don't... I don't want to go in there. It's dark. And it smells funny. Can't we just go home? Please? I promise I'll be good. I won't break anything. I just... I just want to go home.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }, { id: "ch-2-3", title: "Gruff Mercenary", text: "Payment first. Always. Don't care about your sob story, your revolution, or your dead king. Gold on the table, then we talk. And don't even think about stiffing me. Last person who tried that... well. Let's just say he doesn't try things anymore.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }],
    3: [{ id: "ch-3-1", title: "Dual Character Scene", text: "KNIGHT: Stand aside, creature. I have business with the tower. DRAGON: Business? How delightful. I haven't had visitors in... oh, three hundred years? Do come in. Mind the fire. KNIGHT: I'm here for the princess. DRAGON: Aren't they all.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }, { id: "ch-3-2", title: "Emotional Creature", text: "You... you're leaving? But I thought we were friends. I gave you my favourite rock! It was shiny and everything. I don't... I don't understand. Did I do something wrong? Was it the time I ate your shoe? Because I said I was sorry about that.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }, { id: "ch-3-3", title: "Narrator with Character Voices", text: "The fox looked up at the crow. 'My, what beautiful feathers you have,' said the fox, his voice dripping with false admiration. The crow, perched high on the branch, puffed her chest with pride. She opened her beak to sing — and the cheese tumbled to the ground.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }],
    4: [{ id: "ch-4-1", title: "Video Game Boss", text: "PHASE ONE: So... the chosen one arrives. How predictable. PHASE TWO: Impressive. But I'm not even trying yet. PHASE THREE: ENOUGH! You want to see true power? THEN WITNESS IT! FINAL: How... how is this possible? No one has ever... You. You are different.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }, { id: "ch-4-2", title: "Creature Transformation", text: "Start as a small, timid creature: 'Hello? Is someone there?' Mid-transformation: 'Something's happening... I can feel it... changing... GROWING...' Full transformation: 'I AM REBORN! The earth trembles beneath me! The sky bows before my wings!'", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }, { id: "ch-4-3", title: "Dying Hero", text: "No... don't cry. Listen to me. You have to keep going. The others... they need you. You were always the strongest. Not me. I was just... stubborn. Promise me. Promise me you'll finish this. That's... that's my girl. Now go. Go!", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }],
    5: [{ id: "ch-5-1", title: "Full Character Reel", text: "Take 1: Whimsical fairy — 'Follow the moonlight, darling. It knows the way.' Take 2: Grizzled space captain — 'Set coordinates for the Outer Rim. And someone get me a drink.' Take 3: Nervous AI — 'I-I don't think I should be feeling this. Is this what humans call... anxiety?' Take 4: Ancient goddess — 'Mortal. You dare summon me? Speak your wish. Choose your words carefully.'", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }, { id: "ch-5-2", title: "Improv Dialogue Chain", text: "Create a conversation between three characters in a spaceship: the captain (calm authority), the engineer (panicking), and the AI (unnervingly cheerful). The engine has just failed. Each character must have at least three lines. Maintain distinct voices throughout.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }, { id: "ch-5-3", title: "Emotional Range Test", text: "Same character, same line, seven emotions: 'I know what you did.' Read it as: suspicious, heartbroken, furious, amused, terrified, disgusted, and finally, with quiet forgiveness. Each read must be distinctly different while maintaining the same character voice.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }],
  },
  medical: {
    1: [{ id: "md-1-1", title: "Patient Information", text: "This medication should be taken once daily with food. Do not crush, chew, or break the tablet. If you miss a dose, take it as soon as you remember unless it is within 4 hours of your next scheduled dose. Common side effects include headache, nausea, and dizziness.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }, { id: "md-1-2", title: "Safety Disclaimer", text: "Tell your doctor about all medications you are currently taking, including prescription and over-the-counter medicines, vitamins, and herbal supplements. This product has not been evaluated by the Food and Drug Administration and is not intended to diagnose, treat, cure, or prevent any disease.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }, { id: "md-1-3", title: "Health Tip", text: "The American Heart Association recommends at least 150 minutes of moderate-intensity aerobic activity per week. That's about 30 minutes a day, five days a week. Walking, swimming, and cycling are all excellent options for maintaining cardiovascular health.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }],
    2: [{ id: "md-2-1", title: "Drug Mechanism", text: "Amlodipine besylate is a dihydropyridine calcium channel antagonist that inhibits the transmembrane influx of calcium ions into vascular smooth muscle and cardiac muscle. This results in peripheral arterial vasodilation and reduced systemic vascular resistance.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }, { id: "md-2-2", title: "Clinical Trial Results", text: "In a randomised, double-blind, placebo-controlled trial of 847 patients with moderate to severe plaque psoriasis, 67% of patients receiving the study drug achieved a PASI 75 response at week 16, compared to 12% in the placebo group. P-value less than 0.001.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }, { id: "md-2-3", title: "Surgical Procedure", text: "The procedure begins with a small incision in the femoral artery. A catheter is advanced through the vasculature under fluoroscopic guidance until it reaches the target lesion in the coronary artery. A balloon is then inflated to compress the plaque against the vessel wall.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }],
    3: [{ id: "md-3-1", title: "Complex Drug Name Read", text: "Pembrolizumab, sold under the brand name Keytruda, is a humanised monoclonal antibody used in cancer immunotherapy. It targets the programmed cell death protein 1 receptor. Dosing for non-small cell lung carcinoma is 200 milligrams administered intravenously over 30 minutes every 3 weeks.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }, { id: "md-3-2", title: "Patient Education Video", text: "Living with type 2 diabetes doesn't mean giving up the things you love. It means understanding how food, exercise, and medication work together to keep your blood glucose in a healthy range. Today, we'll learn about glycaemic index and how to make meal choices that help stabilise your levels throughout the day.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }, { id: "md-3-3", title: "Adverse Events Warning", text: "Serious adverse reactions include hepatotoxicity, interstitial lung disease, severe dermatological reactions including Stevens-Johnson syndrome, and immune-mediated colitis. Patients should be monitored for signs of hepatic impairment including jaundice, dark urine, and elevated transaminases.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }],
    4: [{ id: "md-4-1", title: "Full ISI Read", text: "IMPORTANT SAFETY INFORMATION: Do not take Zynthera if you are allergic to baricitinib or any of the ingredients in Zynthera. Zynthera may cause serious side effects including serious infections, cancer, blood clots, tears in the stomach or intestines, and changes in certain laboratory test results. Your healthcare provider should check you for tuberculosis before starting Zynthera.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }, { id: "md-4-2", title: "CME Lecture", text: "The pathophysiology of atrial fibrillation involves multiple re-entrant circuits within the atrial myocardium, often initiated by ectopic foci originating from the pulmonary veins. Recent evidence suggests that atrial fibrosis, inflammation, and autonomic nervous system dysfunction all contribute to the substrate maintenance of the arrhythmia.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }, { id: "md-4-3", title: "Emergency Protocol", text: "In the event of anaphylaxis: administer epinephrine 0.3 milligrams intramuscularly into the anterolateral thigh. May repeat every 5 to 15 minutes as needed. Simultaneously establish IV access with normal saline. Prepare for possible endotracheal intubation if airway compromise is suspected.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }],
    5: [{ id: "md-5-1", title: "Full DTC Commercial Script", text: "Are you living with the unpredictable flares of ulcerative colitis? Entyvio may help. In clinical studies, more patients taking Entyvio achieved and maintained remission versus placebo. Entyvio is not for everyone. Tell your doctor if you have an infection, are planning to have or have recently received a vaccine, or are planning to become pregnant. Serious allergic reactions can happen. Call your doctor right away if you experience difficulty breathing, swelling, or rash. The most common side effects include cold symptoms, headache, and joint pain. You are not your UC. Ask your gastroenterologist about Entyvio.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }, { id: "md-5-2", title: "Rapid Safety Disclaimer", text: "Side effects may include nausea, vomiting, diarrhoea, abdominal pain, decreased appetite, upper respiratory tract infection, headache, dizziness, rash, pruritus, fatigue, and insomnia. Serious side effects include hepatotoxicity, pancreatitis, and severe hypersensitivity reactions. See full prescribing information at the website shown on screen.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }, { id: "md-5-3", title: "Research Paper Abstract", text: "BACKGROUND: Immune checkpoint inhibitors have transformed the treatment landscape for advanced melanoma. However, acquired resistance remains a significant clinical challenge. METHODS: We conducted a phase II, open-label, single-arm trial evaluating the combination of nivolumab and relatlimab in 120 patients with unresectable stage III or IV melanoma who had progressed on prior anti-PD-1 therapy.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }],
  },
  promo: {
    1: [{ id: "pr-1-1", title: "TV Show Promo", text: "Tonight on Channel 5 — the drama that everyone is talking about. New episode. New secrets. New betrayals. Riverside, tonight at nine.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }, { id: "pr-1-2", title: "Radio Station ID", text: "Non-stop hits, all day long. This is Power 98.7 — your city's number one for music.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }, { id: "pr-1-3", title: "Event Announcement", text: "This Saturday at Riverside Arena — live music, food trucks, and family fun from noon to midnight. Free entry for kids under 12. The Summer Bash — this Saturday only.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }],
    2: [{ id: "pr-2-1", title: "Movie Trailer", text: "From the director of Nightfall... comes a story of courage, sacrifice, and one impossible choice. This Christmas, prepare for the journey of a lifetime. The Northern Pass. In theatres December 20th.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }, { id: "pr-2-2", title: "Sports Promo", text: "Two teams. One trophy. Zero second chances. The Championship Final — live this Sunday at 4. Only on ESPN. Who wants it more?", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }, { id: "pr-2-3", title: "News Open", text: "Breaking developments tonight. Live coverage as it happens. This is Action News at Ten — with Sarah Mitchell, David Chen, and meteorologist Lisa Park. Your city. Your news. Right now.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }],
    3: [{ id: "pr-3-1", title: "Network Brand Promo", text: "Stories that move you. Characters you won't forget. Drama that stays with you long after the credits roll. This is NBC — and this fall, we're bringing you the best television on the planet.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }, { id: "pr-3-2", title: "Streaming Launch", text: "Everything you love. Nothing you don't. Unlimited movies, series, and originals you can't find anywhere else. StreamVault launches March 1st. The future of entertainment starts now.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }, { id: "pr-3-3", title: "Award Show Tease", text: "The red carpet. The speeches. The moments that define a generation. The 96th Academy Awards — live, this Sunday. Only on ABC.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }],
    4: [{ id: "pr-4-1", title: "Dramatic Anthology", text: "Every week, a new story. Every story, a new world. Tales from the Unknown — where nothing is what it seems, and everything has a price. New episodes, Fridays at 10.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }, { id: "pr-4-2", title: "Podcast Trailer", text: "In 1987, a small town in Oregon went silent. Not metaphorically. Literally silent. No phones. No radio. No voices. For 72 hours, the town of Millhaven simply... stopped. This is the story of what happened in those 72 hours. And why no one has talked about it since. Silence Falls — a new podcast, available everywhere.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }, { id: "pr-4-3", title: "Season Finale Promo", text: "All season long, you've watched. You've guessed. You've argued about it at work. Tonight... the truth. The season finale of The Architect — and nothing will ever be the same. Tonight at 9. Only on HBO.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }],
    5: [{ id: "pr-5-1", title: "Full Imaging Package", text: "Station ID: 'Power 98.7 — your city's heartbeat.' Sweeper: 'More music. Less talk. Power 98.7.' Jingle out: 'You're listening to Power.' Promo: 'This weekend — the Power 98.7 Summer Concert Series returns. Three stages. Twelve artists. One unforgettable weekend. Tickets at power987.com.'", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }, { id: "pr-5-2", title: "Cinematic Universe Trailer", text: "They called them myths. Legends. Fairy tales told to frighten children. But the old stories were warnings. And the warnings... were true. This summer, five heroes. One world. No second chances. Marvel Studios presents: The Convergence. In theatres and IMAX, July 4th.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }, { id: "pr-5-3", title: "Live Event Cold Open", text: "Ladies and gentlemen... from the Dolby Theatre in Hollywood, California... live around the world... this... is the 96th Annual Academy Awards. Please welcome your host for this evening — two-time Oscar nominee, star of The Morning Show and Friends — JENNIFER ANISTON!", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }],
  },
  podcast: {
    1: [{ id: "po-1-1", title: "Conversational Intro", text: "Hey everyone, welcome back to another episode. I'm really excited about today's topic because it's something I've been thinking about for weeks. If you're new here, welcome — hit that subscribe button and let's dive in.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }, { id: "po-1-2", title: "Documentary Opening", text: "On the morning of March 15th, 2019, the residents of Pinewood Avenue woke to find that the oldest oak tree in their neighbourhood — a tree that had stood for over two hundred years — had vanished. Not fallen. Not cut down. Vanished.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }, { id: "po-1-3", title: "Sponsor Read", text: "Today's episode is brought to you by Athletic Greens. Look, I've been using AG1 for about six months now, and honestly, it's the one supplement I actually remember to take. One scoop, 75 vitamins and minerals, and I'm out the door. Try it free at athleticgreens.com/linerunner.", passCriteria: { consistencyMin: 70, timingAccuracyMin: 60, deliveryConfidenceMin: 65 } }],
    2: [{ id: "po-2-1", title: "Interview Setup", text: "My guest today has spent thirty years studying the science of sleep — and what she's discovered might change how you think about every night you've ever had. Dr. Sarah Chen is a neuroscientist at Stanford, and her new book, The Third Shift, has been on the New York Times bestseller list for eleven weeks. Sarah, welcome to the show.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }, { id: "po-2-2", title: "True Crime Narrative", text: "The 911 call came in at 2:47 AM. A woman's voice, barely above a whisper: 'There's someone in my house.' The dispatcher asked for her address. Silence. Then: 'He's on the stairs.' The line went dead. When officers arrived eleven minutes later, the front door was wide open. The house was empty.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }, { id: "po-2-3", title: "Explainer Segment", text: "So here's the thing about inflation that most people get wrong. It's not about prices going up. It's about money being worth less. And the difference matters. Because when you understand that distinction, you start to see why the solutions everyone argues about on Twitter are mostly missing the point.", passCriteria: { consistencyMin: 75, timingAccuracyMin: 70, deliveryConfidenceMin: 70 } }],
    3: [{ id: "po-3-1", title: "Emotional Story Beat", text: "And that was the moment — standing in the middle of a parking lot in suburban New Jersey at 6 AM — that she realised she had been living someone else's life for twenty-three years. Not dramatically. Not in some movie-of-the-week way. Just... quietly. One small compromise at a time.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }, { id: "po-3-2", title: "Science Communication", text: "The James Webb Space Telescope doesn't see light the way we do. It sees infrared — heat radiation — which means it can look through dust clouds that have blocked our view of the early universe for decades. And what it found behind those clouds? Galaxies that shouldn't exist. Galaxies so massive and so old that our current models of cosmic evolution simply cannot explain them.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }, { id: "po-3-3", title: "Debate Moderation", text: "Interesting point. But let me push back on that for a second. You said the data supports your position, but the study you're citing was conducted on a sample of just 200 participants in a single geographic region. How confident can we really be in generalising from that? Convince me.", passCriteria: { consistencyMin: 80, timingAccuracyMin: 75, deliveryConfidenceMin: 75 } }],
    4: [{ id: "po-4-1", title: "Long-Form Narrative", text: "This is a story about a bridge. Not a famous one. Not a beautiful one. A concrete overpass on Highway 12 in central Iowa that 40,000 cars cross every day without a second thought. But in 1991, an engineer named David Reeves noticed something that no one else had seen — a crack, barely visible, running along the main support beam. What happened next would change American infrastructure policy forever.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }, { id: "po-4-2", title: "Comedy Timing", text: "So my therapist says, 'Tell me about your relationship with your mother.' And I say, 'Which version do you want — the one I tell at dinner parties, or the one that wakes me up at 3 AM?' She didn't laugh. Therapists never laugh. Which, honestly, is why they need therapists.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }, { id: "po-4-3", title: "Cliffhanger Ending", text: "And that's where we have to leave it this week. I know. I KNOW. But next Thursday, we're going to hear the recording that changed everything. The one the police didn't want released. The one that proves — beyond any reasonable doubt — that what happened on that mountain was not an accident. See you next week. And maybe... lock your doors tonight.", passCriteria: { consistencyMin: 85, timingAccuracyMin: 80, deliveryConfidenceMin: 80 } }],
    5: [{ id: "po-5-1", title: "Series Premiere", text: "Welcome to Frequency — a new podcast about the sounds that shaped the modern world. I'm your host, and over the next twelve episodes, we're going to travel from the recording studios of 1940s Nashville to the server farms of Spotify, asking one simple question: what happens when music stops being heard and starts being consumed? This is Episode One: The Death of Silence.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }, { id: "po-5-2", title: "Multi-Voice Documentary", text: "NARRATOR: The factory closed on a Friday. WORKER 1: They told us at lunch. Just... at lunch. Like it was nothing. NARRATOR: Six hundred jobs. Gone. MAYOR: We had no warning. None. NARRATOR: But the documents tell a different story. A story that begins not in this town, but in a boardroom 3,000 miles away.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }, { id: "po-5-3", title: "Series Finale", text: "And so we arrive at the end. Not the end of the story — because stories like this one don't end. They just change shape. But the end of our time together, at least for now. Thank you for listening. Thank you for caring. Thank you for the thousands of messages, the theories, the arguments, and the late-night rabbit holes. This has been Frequency. I'm your host. And the next sound you hear... is up to you.", passCriteria: { consistencyMin: 90, timingAccuracyMin: 85, deliveryConfidenceMin: 85 } }],
  },
};
